### ISSUE TITLE
feature request: allow for different ports

### ISSUE THREAD

**Issue by dignifiedquire** [rkuhn/swarm-discovery#1]
Currently peer information is limited to a single port, but I actually need to advertise multiple ip address + port combinations, maybe instead of `Vec<IpAddr> + u16`, it could be `Vec<SocketAddr>`?

**Comment by rkuhn** [comment]
Yes, that should be possible, one single u16 “port” is required by mDNS, though (unless I’m mistaken). The port-per-service information would go into TXT record(s). So the logical data package would be

- list of IP–port pairs
- one u16

Does that work for you?

**Comment by dignifiedquire** [comment]
yes, that should work well

**Comment by rkuhn** [comment]
released in v0.2.0
