### ISSUE TITLE
improve IPv4/v6 usage with default settings

### ISSUE THREAD

**Issue by rkuhn** [rkuhn/swarm-discovery#4]
The current default behaviour is to open sockets both for IPv4 and IPv6, which may fail. A better default might be a new `IpClass::Auto` setting that tries both and only errors when none work.

@ramfox you looked into this a bit, please don’t hesitate to add more details or suggestions! At first I thought about only trying IPv6 once we’re advertising such an address, but that doesn’t cover the use case of listening to an IPv6-only swarm.

**Comment by ramfox** [comment]
`IpClass::Auto` was the exact thing I was hoping for.

**Comment by ramfox** [comment]
thought I'd take a stab at it: https://github.com/rkuhn/swarm-discovery/pull/5
